# Generated by Django 4.2.2 on 2023-06-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('cholesterol', models.IntegerField()),
                ('blood_pressure', models.IntegerField()),
                ('blood_sugar', models.CharField(max_length=10)),
                ('resting_ecg', models.CharField(max_length=50)),
                ('max_heart_rate', models.IntegerField()),
                ('exercise_induced_angina', models.BooleanField()),
                ('st_depression', models.FloatField()),
                ('st_slope', models.CharField(max_length=50)),
                ('num_major_vessels', models.IntegerField()),
                ('thalassemia', models.CharField(max_length=50)),
                ('diagnosed', models.BooleanField(default=False)),
            ],
        ),
    ]
